AllCops:
  Exclude:
    - 'db/**/*.rb'
    - 'test/test_helper.rb'

Metrics/BlockLength:
  Exclude:
    - 'test/features/*.rb'

Metrics/LineLength:
  Exclude:
    - 'test/features/*.rb'

Metrics/ClassLength:
  Exclude:
    - 'test/features/*.rb'
